### ISSUE TITLE
Subsplit don't work one time out of two

### ISSUE THREAD

**Issue by yuters** [dflydev/dflydev-git-subsplit-github-webhook#2]
After a couple of call to the webhook, I have this message :

`Skipping request for URL git@host:project.git (not configured)`

If I call the webhook again with the same info, it works. 

It does the same every 2 times.

**Comment by simensen** [comment]
Would it be possible to attach your configuration? How are you calling the hook? Manually?

Is it possible you have multiple instances of the worker running? One that is still running from a  previous config in which that/those particular URLs had not yet been configured?

**Comment by yuters** [comment]
Good lord. You're right. I had two processes running!

Thanks a lot :)

**Comment by simensen** [comment]
Sure thing. :)

I'll have to put that in a FAQ somewhere.
